


# Remap prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind a send-prefix

bind r source-file ~/.tmux.conf


# List of Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize tpack (This line must be last.)
run 'tpack init'
